napalm-automation/napalm-base

napalm_base/base.py
napalm_base/test/base.py
napalm_base/test/models.py

Retrieves users configured on the device

Define get_users()

---

napalm_base/test/base.py

@dbarrosop I made a small mistake here :D

test_traceroute correction

---

.travis.yml
napalm_base/helpers.py
test/unit/TestHelpers.py
test/unit/templates/__a_very_nice_template__.j2
test/unit/templates/__completely_wrong_template__.j2
test/unit/utils/textfsm_templates/__a_very_nice_template__.tpl
test/unit/utils/textfsm_templates/__completely_wrong_template__.tpl

I find both functions very useful and needed more and more. In order to not define them again and again in each driver class, I think we should include them in the helpers module (actually that was their purpose) and use wherever needed.

find_txt and convert functions in helpers

---

napalm_base/base.py
napalm_base/helpers.py
test/custom/path/base/__a_very_nice_template__.j2
test/unit/TestHelpers.py

Regarding the discussion with @dbarrosop in #6.
load_template is documented in the base class, but if necessary, we can copy it here too. Or we can define it in the helper function and load the docstring dynamically in the method :P

Load_template: load from custom path

---

napalm_base/__init__.py
napalm_base/exceptions.py
setup.py
test/unit/TestGetNetworkDriver.py
test/unit/requirements.txt

@dbarrosop @ktbyers @hurrycane @privateip Any thoughts about that?
No documentation yet, but I will provide in case we all agree this looks and feels better.

New implementation for get_network_driver

---

setup.py

Addresses https://github.com/napalm-automation/napalm/issues/249
Related to https://github.com/napalm-automation/napalm/pull/250

Fix clitools entry point.

---

.travis.yml
napalm_base/test/base.py
test/unit/TestNapalmTestFramework.py

Currently, Napalm tests have many NotImplementedErrors due to devices not having all features.  As a dev and longtime TDD guy, I'm accustomed to running my tests, and having them either pass or fail.  I find that false negatives clutter my test runs and interrupt my dev "flow", eg:
```
(venv) ~/Documents/Projects/napalm-nxos$ python -m unittest test.unit.TestNXOSDriver
.E.EE..E......EEE..E....
... lots of (intentional) error noise ...
```
This PR checks for NotImplementedErrors for each method call, and if that error is raised, it skips the test.  Here's the same test run after the patch is applied:
```
(venv) ~/Documents/Projects/napalm-nxos$ python -m unittest test.unit.TestNXOSDriver
.s.ss..s......sss..s....
----------------------------------------------------------------------
Ran 24 …
```

Skip tests if NotImplementedError is thrown.

---

napalm_base/clitools/cl_napalm_configure.py
napalm_base/clitools/cl_napalm_test.py
napalm_base/clitools/helpers.py
setup.py

In my proposal https://github.com/napalm-automation/napalm/pull/267, @jzohrab suggested that a script to test the connectivity would be very handy.
I propose a script called ```cl_napalm_test```, reusing some parts of the code from ```cl_napalm_configure```.

Test connectivity script

---

napalm_base/base.py
napalm_base/test/base.py
napalm_base/test/models.py

Fixes #50.
Nice catch @inetuid!

advertised_prefix_count key

---

napalm_base/helpers.py

Comes together with ```mac``` (https://github.com/napalm-automation/napalm-base/pull/54) to prepare the eggs for the upcoming cleanup/hackathon.

New helper: ip

---

napalm_base/base.py
napalm_base/test/base.py
napalm_base/test/models.py

Similar to ```get_ntp_peers```, retrieves the configuration of the NTP servers.

Add get_ntp_servers()

---

napalm_base/base.py
napalm_base/test/base.py
napalm_base/test/models.py

Related to napalm-automation/napalm-base#65
@napalm-automation/council thoughts? Will send EOS implementation as a POC.

Added get_config method

---

napalm_base/__init__.py

As per slack conversation during napalm-hackathon-2016.

Fix for bug when not installed.

---

napalm_base/helpers.py
test/unit/TestHelpers.py

@dbarrosop @ktbyers please review

Enhance helpers

---

napalm_base/__init__.py
napalm_base/base.py
napalm_base/clitools/cl_napalm_configure.py
napalm_base/clitools/cl_napalm_test.py
napalm_base/clitools/helpers.py
napalm_base/helpers.py
napalm_base/test/base.py
napalm_base/test/models.py
pylama.ini

This should be all pylama cleanup. Please test, however.

pylama cleanup of napalm-base

---

vagrant/Vagrantfile

Added ros box

---

napalm_base/__init__.py

Reverts napalm-automation/napalm-base#92 from master branch. #96  comes with the necessary fix in the develop branch and all the changes will be part of the master when releasing

Revert "Fix for bug when not installed."

---

napalm_base/helpers.py

Add newline to pass build tests

Add newline to pass build test

---

setup.py

Releasing for https://github.com/napalm-automation/napalm-base/pull/139

Version bump to 0.19.2

---

napalm_base/utils/string_parsers.py

As per comment from @dbarrosop on https://github.com/napalm-automation/napalm-ros/pull/22

Added ROS format uptime string to convert_uptime_string_seconds()

---

napalm_base/constants.py

As per our previous discussion in https://github.com/napalm-automation/napalm-junos/pull/81

Constants napalm-base module

---

napalm_base/validate.py
test/unit/validate/mocked_data/non_strict_fail/get_route_to.json
test/unit/validate/mocked_data/non_strict_fail/report.yml
test/unit/validate/mocked_data/non_strict_fail/validate.yml
test/unit/validate/mocked_data/non_strict_pass/get_route_to.json
test/unit/validate/mocked_data/non_strict_pass/report.yml
test/unit/validate/mocked_data/non_strict_pass/validate.yml
test/unit/validate/mocked_data/strict_fail/get_route_to.json
test/unit/validate/mocked_data/strict_fail/report.yml
test/unit/validate/mocked_data/strict_fail/validate.yml
test/unit/validate/mocked_data/strict_pass/get_route_to.json
test/unit/validate/mocked_data/strict_pass/report.yml
test/unit/validate/mocked_data/strict_pass/validate.yml

Need to add some unit tests before merging.

Fixed and issue comparing lists of dicts

---

.travis.yml
napalm_base/base.py
napalm_base/helpers.py
napalm_base/validate.py
napalm_base/yang_helpers.py
requirements.txt
setup.py
test/unit/validate/mocked_data/non_strict_fail/get_route_to.json
test/unit/validate/mocked_data/non_strict_fail/report.yml
test/unit/validate/mocked_data/non_strict_fail/validate.yml
test/unit/validate/mocked_data/non_strict_pass/get_route_to.json
test/unit/validate/mocked_data/non_strict_pass/report.yml
test/unit/validate/mocked_data/non_strict_pass/validate.yml
test/unit/validate/mocked_data/strict_fail/get_route_to.json
test/unit/validate/mocked_data/strict_fail/report.yml
test/unit/validate/mocked_data/strict_fail/validate.yml
test/unit/validate/mocked_data/strict_pass/get_route_to.json
test/unit/validate/mocked_data/strict_pass/report.yml
test/unit/validate/mocked_data/strict_pass/validate.yml
test/unit/validate/mocked_data/strict_pass_skip/report.yml
test/unit/validate/mocked_data/strict_pass_skip/validate.yml

We can now specify how to retrieve the data on the parser file. See napalm-automation/napalm-eos#135.
Fixes #195 and #196

YANG API is now more general

---

napalm_base/validate.py
test/unit/validate/mocked_data/non_strict_fail/validate.yml
test/unit/validate/mocked_data/non_strict_pass/validate.yml
test/unit/validate/mocked_data/strict_fail/validate.yml
test/unit/validate/mocked_data/strict_pass/get_lldp_neighbors.json
test/unit/validate/mocked_data/strict_pass/report.yml
test/unit/validate/mocked_data/strict_pass/validate.yml
test/unit/validate/mocked_data/strict_pass_skip/validate.yml

This PR fixes https://github.com/napalm-automation/napalm-base/issues/201 and is built on top of https://github.com/napalm-automation/napalm-base/pull/202
It includes tests as well.

Fix issues #201

---

napalm_base/utils/string_parsers.py
setup.py
test/unit/TestHelpers.py

Fixes bug with with uptime string parser

Improvements to uptime string parser

---

napalm_base/base.py

Fixes https://github.com/napalm-automation/napalm-ios/issues/135
@gjim83 @mirceaulinic comments?

Check if connection is alive before closing

---

napalm_base/test/base.py

@luqasz would you care testing, please?

Making testing configuration changes pytest compatible

---

setup.py

And update authors, adding @ktbyers and myself.

Prepare release 0.24.0

---

napalm_base/base.py

It is helpful to have a reference example.

Documentation only: add reference example for get_bgp_neighbors

---

test/unit/test_indent_differ.py
test/unit/test_indent_differ/test_case_3/candidate.txt
test/unit/test_indent_differ/test_case_3/cli.1.show_running_config.0
test/unit/test_indent_differ/test_case_3/diff.txt

Test case to mess up ordering of access-lists.

Test ACL ordering

---

test/unit/test_indent_differ.py

@dbarrosop, I'm guessing there might be a reason why you didn't do this from the start. Anyway it feels like it should be there.

Load tests automatically

---

napalm_base/validate.py
test/unit/validate/mocked_data/non_strict_fail/report.yml
test/unit/validate/mocked_data/simple_fail/get_facts.json
test/unit/validate/mocked_data/simple_fail/report.yml
test/unit/validate/mocked_data/simple_fail/validate.yml
test/unit/validate/mocked_data/strict_fail/report.yml
test/unit/validate/test_unit.py
test/unit/validate/test_validate.py

Solves #290 
Ping @ktbyers @bdlamprecht

Add requested value to the validate report

---

setup.py

Version 0.25.0

---

napalm_base/base.py
test/unit/validate/test_validate.py

Update base.py and add tests.
Remember the change is backwards incompatible (default value has changed)

Add tests for validation from source
