napalm_base/base.py
napalm_base/test/base.py

@mirceaulinic can you review this? What do you think?
The idea is to be able to treat this method in a more natural way, passing what I want in the template as named arguments:
```
driver.load_template('set_ntp_peers', peers=['1.1.1.1', '2.2.2.2'])
```
Alternatively, I wouldn't mind passing a dict, something like:
```
driver.load_template('set_ntp_peers', {'peers': ['1.1.1.1', '2.2.2.2']})
```
So in the template you can do:
```
{% for peer in peers %}
peer {{peer}}
{% endfor %}
```
Instead of:
```
{% for peer in template_vars %}
peer {{peer}}
{% endfor %}
```
Thoughts?

load_template now accepts **args as it feels more natural

---

napalm_base/base.py
napalm_base/test/base.py
napalm_base/test/models.py

This refers to RPM probes on JunOS and SLA probes on IOS-XR.
On EOS is might be possible to add custom probes. Will investigate that.

Define get_probes_config() and get_probes_results()

---

napalm_base/__init__.py

This commit replaces the static loading of drivers with a dynamic loader.  The
dynamic loader can load modules using either a full path namespace
or a single module name.  If the provided name is not a full path
namespace, then the module name is prepended with the default namespace.
For example, calling get_network_driver('foo') will be translated to
'napalm_foo.foo' but get_network_driver('napalm.foo') will not be
modified.

replaces static loader with dynamic loader

---

napalm_base/__init__.py

@privateip could you take a look? I made a few changes, the idea is as follow:
1. First I made most methods `internal`.
2. I changed how `get_network_driver` works. Now it will:
1. If `load_driver` exists in `module` it returns whatever that method returns.
2. If `load_driver` doesn't exist it will inspect all objects in `module` and return the first class that is a subclass of `NetworkDriver`.
This way you can either add `load_driver` to your module if you need/want to do something when fetching the driver or you can just add the line `from eos import EOSDriver`.

get_network_driver will attempt to find the driver if load_driver doesnt exist

---

napalm_base/__init__.py
napalm_base/base.py
napalm_base/helpers.py

Also need to move the templates in all napalm_*:
Noticed they still reside under /templates/[DRIVER_NAME]/ instead of /templates/

Moved load_template() and textfsm_extractor() in helpers module

---

napalm_base/base.py
napalm_base/test/base.py
napalm_base/test/models.py

The actual method get_ntp_peers() returns a dictionary with the statistics of the configured NTP peers. It would feel more natural to be called get_ntp_stats(). For the reasons presented below, we need to implement a different method get_ntp_peers() to retrieve the NTP config.
Unfortunately the current implementation of get_ntp_peers() be used to determine the NTP peers configured on the device (at least on JunOS which returns the raw output of the _ntpq_ Unix daemon), where the columns have a max width of 15 characters:
```
-2400:cb00:22:10 162.158.5.4      5 u  886 1024  377  139.385  -14.783   4.655
```
```2400:cb00:22:10``` obviously is not a valid IPv6 address so, right now, get_ntp_peers() cannot be completely reliable in terms of remote NTP address.
Actions needed:
- since the …

NTP stats getter to replace NTP peers getter

---

napalm_base/test/models.py

Small change for get_probes_results()
See https://github.com/napalm-automation/napalm-base/pull/9

get_probes_results(): last_test_loss replaces current_test_loss

---

napalm_base/base.py
napalm_base/test/base.py
napalm_base/test/models.py

As discussed in https://github.com/napalm-automation/napalm-base/pull/12, will reimplement get_ntp_peers() to return a list of NTP peers as configured on the device.

Add get_ntp_peers()

---

napalm_base/helpers.py

When using the following template:
```
Value Required if_name (.+)
Value flags (.+)
Value mtu (\d+)
Value qdisc (.+)
Value state (\w+)
Value link_type (.+)
Value mac_address (.+)
Value List ipv4_addresses (.+)
Value List ipv6_addresses (.+)
Start
^\d+: [^:]+\: < -> Continue.Record
^\d+: ${if_name}\: <${flags}> mtu ${mtu} qdisc ${qdisc} state ${state}
^\s+link/${link_type}\s+${mac_address}\s+brd
^\s+inet ${ipv4_addresses}\s+scope 
^\s+inet6 ${ipv6_addresses}\s+scope 
```
against this input:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 16436 qdisc noqueue state UNKNOWN 
link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
inet 127.0.0.1/8 scope host lo
inet 10.65.0.1/32 scope global lo
inet 10.65.0.254/32 scope global lo
inet6 ::1/128 scope host 
valid_lft forever preferred_lft forever
2: eth0: …
```

Fix so that textfsm_extractor() does not clobber all types to string.

---

napalm_base/base.py
napalm_base/test/base.py
napalm_base/test/models.py

Proposal to add the vrf key in the layer 1 dictionary of the output for ```get_bgp_neighbors_detail```.
Will fix https://github.com/napalm-automation/napalm-junos/issues/28 too.
I think we can take this chance to add the ```router_id```: see https://github.com/napalm-automation/napalm-base/issues/40

Structure adjust for get_bgp_neighbors_detail

---

napalm_base/helpers.py
test/unit/TestHelpers.py

I think it's time to have a standard in the format of the MAC Addresses.
Easy to use:
```python
from napalm_base.helper import mac
mac('0123.4567.89ab')
```

New helper: mac

---

requirements.txt
setup.py

Seems like `netaddr` was missing from the `requirements.txt` file.
Will release a quick fix once this is approved.

Added missing requirement

---

napalm_base/__init__.py
napalm_base/helpers.py
setup.py

Added find_version() to both the setup.py file for napalm_base and to helpers.py.
Other packages should just be able to add the following into their setup.py
```
from napalm_base.helpers import find_version
```

Add find_version to napalm_base

---

napalm_base/__init__.py
napalm_base/helpers.py
napalm_base/system_helpers.py
setup.py

```
$ pip install -r requirements.txt
Collecting napalm-base (from -r requirements.txt (line 1))
Downloading napalm-base-0.16.0.tar.gz (232kB)
100% |################################| 233kB 1.8MB/s 
Traceback (most recent call last):
File "<string>", line 20, in <module>
File "/tmp/pip-build-3bUemy/napalm-base/setup.py", line 6, in <module>
from napalm_base.helpers import find_version
File "napalm_base/__init__.py", line 24, in <module>
from napalm_base.base import NetworkDriver
File "napalm_base/base.py", line 20, in <module>
import napalm_base.helpers
File "napalm_base/helpers.py", line 9, in <module>
import jinja2
ImportError: No module named jinja2
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 20, in <module>
File …
```

We need those system helpers to work without importing 3d party libraries

---

napalm_base/test/getters.py

Previous import statement won't work under Python3. Was causing Python3 test failures in napalm-eos.

Fix python3 import bug

---

napalm_base/test/double.py

Old behaviour:
```python
>>> text = 'my text has > and \ and $ ...'
>>> re.sub(regexp, '_', text)[0:150]
'my_text_has_>_and_\\_and___...'
```
New:
```python
>>> re.sub(regexp, '_', text)[0:150]
'my_text_has____and___and______'
```
Changes: ```\```, ```>```, ```<```, ```:``` and ```.``` are replaced now by ```_```.
The colon & period chars replacement will impact the existing tests under napalm-eos, and filenames under the tests for [get_bgp_neighbors](https://github.com/napalm-automation/napalm-eos/tree/develop/test/unit/mocked_data/test_get_bgp_neighbors) will need to be renamed, e.g.: https://github.com/napalm-automation/napalm-eos/blob/develop/test/unit/mocked_data/test_get_bgp_neighbors/normal/show_ip_bgp_neighbors_vrf_all___include_remote_AS___remote_router_ID__IPv_46__Unicast:.__0-9_ …

Strip more characters

---

napalm_base/base.py
napalm_base/test/base.py
napalm_base/test/getters.py
napalm_base/test/models.py

There are cases when the connection is open correctly, the driver stays connected for minutes/hours/days, but due to external factors, the connection is dropped (packet loss, or the device simply kills the process etc.).
In that case, we need to know when the connection become unusable and reconnect.

New method: is_alive()

---

napalm_base/base.py
napalm_base/test/base.py
napalm_base/test/getters.py
napalm_base/test/models.py

Proposal to add a method to retrieve configured VRFs and their associated interfaces from a device.

Add method .get_vrfs()

---

napalm_base/base.py
napalm_base/test/base.py
napalm_base/test/getters.py
napalm_base/test/models.py

It would be nice to have an output of all configured Firewall policies. In an easy and parseable way.
For this I would propose to use the method get_firewall_policies .
Output:
`>>> device.get_firewall_rules()
{'1': {'uuid': '9d747de8-dad4-51e5-7a7e-d078aa77140a', 'service': '"ALL"', 'schedule': '"always"', 'srcaddr': '"all"', 'dstintf': '"any"', 'srcintf': '"any"', 'action': 'accept', 'dstaddr': '"all"'}, '2': {'name': '"bla"', 'service': '"ALL"', 'schedule': '"always"', 'logtraffic': 'all', 'srcaddr': '"all"', 'dstintf': '"port2"', 'srcintf': '"port3"', 'dstaddr': '"all"', 'uuid': 'de597b64-aca8-51e6-5d00-b7874e6b72b8'}}`
I already implemented the feature for FortiOS:
https://github.com/napalm-automation/napalm-fortios/pull/22

Implementation of get_firewall_policies

---

napalm_base/test/getters.py

Python3 inspect.ismethod() requires a bound object.
Consequently, the following line was always reporting as True (and the method signature checks were being skipped).
```
if attr.startswith('_') or not inspect.ismethod(func):
continue
```

Fixing issues with Python3 and method signature check

---

napalm_base/exceptions.py
napalm_base/validate.py

Refers to #83
Here I'm adding validation capabilities to napalm-base. This means that we'll be able to validate getters method results and running/candidate configuration as well.
Sample `validate.yml`
```
---
get_interfaces:
Ethernet2/5:
is_enabled: true
is_up: false
loopback103:
is_enabled: false
is_up: false
Vlan100:
is_enabled: false
is_up: false
get_facts:
os_version: 7.0(3)I2(2d)
interface_list:
- Vlan5
- Vlan100
hostname: n9k2
get_lldp_neighbors:
mgmt0:
- hostname: PERIMETER
port: Fa1/0/3
- hostname: nxos-spine2
port: nxos-spine2
get_bgp_neighbors:
default:
router_id: 192.0.2.2
peers:
192.0.2.3:
is_enabled: false
192.0.2.2:
is_enabled: false
address_family:
ipv4:
sent_prefixes: 5
ipv6:
sent_prefixes: 2
get_arp_table:
- interface: Ethernet2/1
ip: 192.0.2.2
get_interfaces_ip: …
```

Adding validation capabilities to the napalm-base

---

napalm_base/clitools/cl_napalm_configure.py
napalm_base/clitools/cl_napalm_validate.py
napalm_base/clitools/helpers.py
setup.py

Sample usage:
```
---
get_facts:
os_version: 7.0(3)I2(2d)
interface_list:
- Vlan5
- Vlan100
hostname: n9k1
get_lldp_neighbors:
Eth1/1:
- hostname: n9k2.ntc.com
port: Ethernet1/1
get_bgp_neighbors:
default:
router_id: 192.0.2.2
peers:
192.0.2.2:
address_family:
ipv4:
sent_prefixes: 5
ipv6:
sent_prefixes: 2
```
```
$ cl_napalm_validate --user test --vendor nxos --validation_file test.yml n9k1 --debug
Enter password: 
2016-12-18 12:50:09,425 - cl_napalm_validate.py - DEBUG - Getting driver for OS "nxos"
2016-12-18 12:50:10,288 - cl_napalm_validate.py - DEBUG - Connecting to device "n9k1" with user "test" and optional_args={}
2016-12-18 12:50:10,734 - cl_napalm_validate.py - DEBUG - Generating compliance report
{
"get_facts": {
"extra": [], 
"complies": false, 
"present": {
"os_version": { …
```

Adding CLI tool for validate

---

napalm_base/validate.py
test/unit/validate/mocked_data/non_strict_fail/validate.yml
test/unit/validate/mocked_data/non_strict_pass/validate.yml
test/unit/validate/mocked_data/strict_fail/get_bgp_neighbors.json
test/unit/validate/mocked_data/strict_fail/report.yml
test/unit/validate/mocked_data/strict_fail/validate.yml
test/unit/validate/mocked_data/strict_pass/validate.yml
test/unit/validate/test_unit.py

The only "problem" is that characters have to be escaped when doing literal comparisons
(I will update the documentation when I get the approval to merge this PR)

You can now use regular expressions to validate data

---

napalm_base/test/helpers.py
test/unit/TestGetNetworkDriver.py
test/unit/requirements.txt
test/unit/requirements_py3.txt

Update test status to reflect NAPALM distributions that have release Python3 support

Update test status to reflect NAPALM distributions that have release Python3 support

---

napalm_base/base.py

Adding a reference to using a "_" key for bgp neighbors not a member of any group.
As per request in: https://github.com/napalm-automation/napalm-iosxr/pull/96

Added reference to '_' as bgp group name

---

napalm_base/base.py
napalm_base/helpers.py
napalm_base/validate.py
test/unit/validate/mocked_data/strict_pass_skip/report.yml
test/unit/validate/mocked_data/strict_pass_skip/validate.yml

Fixes #180
This adds a special keyword `_name` you can add to a getter to override the name in the report. Useful for being descriptive or for getters that accept arguments and can actually be used more than once in the same report.

Added special keyword _name to override name in the report

---

setup.py

Preparing 0.23.0 for https://github.com/napalm-automation/napalm-base/pull/185
Although it's not a new method, I think we should cut a major release as this is still an API change. Does this make sense?

Version 0.23.0

---

napalm_base/base.py

Otherwise, an `OSError` exception is thrown during garbage collection when the session was already closed.

Adding check to __del__ to ignore exception if socket was already closed

---

napalm_base/validate.py
test/unit/validate/mocked_data/non_strict_fail/get_environment.json
test/unit/validate/mocked_data/non_strict_fail/report.yml
test/unit/validate/mocked_data/non_strict_fail/validate.yml
test/unit/validate/mocked_data/non_strict_pass/get_environment.json
test/unit/validate/mocked_data/non_strict_pass/report.yml
test/unit/validate/mocked_data/non_strict_pass/validate.yml
test/unit/validate/mocked_data/strict_pass/get_environment.json
test/unit/validate/mocked_data/strict_pass/report.yml
test/unit/validate/mocked_data/strict_pass/validate.yml

Hi,
I needed numeric compare when pre-post validate such as cpu_use,memory_available.
for example, less than memory 50% is executed by commit_config.
* modified: _compare_getter_dict
* add method: compare_numeric
* add test: get_environment

Add numeric compare for validation

---

napalm_base/exceptions.py

Define new exception `ConnectionClosedException` as per https://github.com/napalm-automation/napalm-base/pull/247
Add the exceptions proposed in https://github.com/napalm-automation/napalm-base/issues/218

More exceptions

---

napalm_base/helpers.py
test/unit/TestHelpers.py

- confusing variable and function have the same name
- fails when the value is already an integer

Fix the as_number helper

---

napalm_base/__init__.py
test/unit/TestGetNetworkDriver.py
test/unit/requirements.txt

Not sure if using napalm-logs to test a real module not having NetworkDriver is correct, or if we should create a specific dummy module to test.  Also test a non-string type to hit 86, napalm_eos to hit cover 94->96 jump.

Improve coverage of get_network_driver()

---

napalm_base/base.py

This commit fixes Issue #267:
[https://github.com/napalm-automation/napalm-base/issues/267](url)
Adding an exception handler for AttributeError allows the script to complete.

Added AttributeError Exception to __del__ function in NetworkDriver

---

napalm_base/indent_differ.py
test/unit/test_indent_differ.py
test/unit/test_indent_differ/test_snmp_server/candidate.txt
test/unit/test_indent_differ/test_snmp_server/cli.1.show_running_config.0
test/unit/test_indent_differ/test_snmp_server/diff.txt

An additional test for #277. It's nice that the code knows how to handle the added `snmp-server community public RO 10` line correctly.
However it doesn't work for the added `snmp-server enable traps entity-sensor` as it thinks it's supposed to delete `snmp-server enable traps entity`. 
There will be a number of these scenarios, probably "a lot". In some instances it will also surely differ between various platforms.

Tests for config under snmp-server (for #277)

---

napalm_base/validate.py

Essence of change is this:
```
+            m = re.search(src, py23_compat.text_type(dst))
+            if m:
+                return bool(m)
+            else:
+                return src == dst
```
Basically try re.search first and if that fails, then look for exact string comparison.
I also eliminated an unnecessary 'else' from the code as it was serving no purpose.

Fix napalm validate so identical strings will work

---

napalm_base/base.py

Fixing a bad link in the documentation for "compliance_report" function.

Correct link under "compliance_report" function

---

napalm_base/base.py
napalm_base/mock.py
test/unit/test_mock_driver.py

Solves #297 
Do not merge yet. Looks like old implementation was good for py3.

__enter__ was swallowing the exception and returning False

---

napalm_base/mock.py

The trend seems to be that more drivers will see the introduction of rpc oriented interfaces. This is especially true as things shift to model based configuration. This PR removes the junos constraint from the `_rpc` method in the MockDriver. 
The specific usecase is to allow `napalm-yang` tests work with an [iosxe](https://github.com/nickethier/napalm-iosxe) driver I'm developing.

Remove constraint on _rpc method for MockDriver

---

napalm_base/base.py
napalm_base/validate.py
test/unit/validate/test_validate.py

Having the validation format in a single place makes the validation
constrained by placing the content only on a single file,
on the local disk.
There are many applicabilities where we need to test with remote
content, or any other source.
This is making the validator more flexible

Validate using python object

---

README.md

Removing the download counter which has stopped working:
[![PyPI](https://img.shields.io/pypi/dm/napalm-base.svg)](https://pypi.python.org/pypi/napalm-base)
It can give the wrong impression of the project. And of course, so that everything looks nice for the hacktoberfest. :)

Remove download counter which no longer works
